---
- name: Reboot Linux Mint
  hosts: all
  become: true
  become_user: administrator
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Berechtigungen überprüfen
      ansible.builtin.command: id
      register: user_check

    - name: Berechtigungen ausgeben
      ansible.builtin.debug:
        var: user_check.stdout

    - name: Client neustarten
      ansible.builtin.reboot:
        reboot_timeout: 600
        post_reboot_delay: 15
